farmers/urls.py
from django.urls import path
from . import views


app_name = 'farmers'

urlpatterns = [
    path('', views.IndexView.as_view(), name='farmers'),
    path('add/', views.AddView.as_view(), name='add-farmer'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('<slug:pk>/', views.SingleView.as_view(), name='details-farmers'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit-farmer'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete-farmer'),
]

mkulima/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("subscriptions/", include("subscription_app.urls")),
    path('warehouses/', include("warehouses.urls")),
    path('connections/', include("farmer_connections.urls")),
    path("farmers/", include("farmers.urls")),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="users/password_reset.html"), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html"), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete")
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users import views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home, name="home"),
    path('profile/', views.profile, name="profile"),
    path('register/', views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(
        template_name="users/logout.html"), name="logout")
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image
from django.conf import settings


# Create your models here.4
class AccountType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    age = models.IntegerField(null=True)
    occupation = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to="pics", default="default.jpg")
    accountType = models.ForeignKey(
        AccountType, on_delete=models.CASCADE, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self):
        return self.user.username + "'s profile"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.db.models import fields

from users.models import AccountType, User, Profile


class AccountTypeForm(forms.ModelForm):
    name = forms.ModelChoiceField(
        queryset=AccountType.objects.all())

    class Meta:
        fields = ['name']


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(label="First Name :", widget=forms.TextInput(
        attrs={'placeholder': 'Enter First Name'}))
    last_name = forms.CharField(label="Last Name:", widget=forms.TextInput(
        attrs={'placeholder': 'Enter Last Name'}))
    email = forms.EmailField(label="Email :", widget=forms.EmailInput(
        attrs={'placeholder': 'Enter Email'}))
    username = forms.CharField(label="Username :", widget=forms.TextInput(
        attrs={'placeholder': 'Enter Username'}))
    password1 = forms.CharField(label="Password : ", required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter Password'}))

    password2 = forms.CharField(label="Password Confirmation: ", required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Your Password'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2']


class ProfileUpdateForm(forms.ModelForm):
    accountType = forms.ModelChoiceField(label="Account Type: ",
                                         queryset=AccountType.objects.all())

    class Meta:
        model = Profile
        fields = ['image', 'occupation', 'age', 'accountType', ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

users/views.py
from django.shortcuts import redirect, render
from users.forms import ProfileUpdateForm, UserRegistrationForm, UserUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from warehouses.models import Warehouses


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f" {username}, your account has been created successfully")
            return redirect("home")
    else:
        form = UserRegistrationForm()

    return render(request, "users/register.html", {'form': form})


def home(request):
    warehouses = Warehouses.objects.all()

    return render(request, "warehouses/warehouses.html",{'warehouses': warehouses})


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile,)

        if p_form.is_valid() and u_form.is_valid():
            p_form.save()
            u_form.save()
            messages.success(
                request, f" your account has been updated successfully")
            return redirect("profile")
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, "users/profile.html", context)

users/templates/users/base.html
<!doctype html>
<html lang="en">
{% load static %} {% load crispy_forms_tags %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <title>
        {% block title %} Mkulima {% endblock title%}
    </title>

    <link href="{% static 'users/styles/bootstrap.min.css' %}" rel="stylesheet">


    <link href="{% static 'users/styles/styles.css' %}" rel="stylesheet">
    <link href="{% static 'users/styles/dashboard.css' %}" rel="stylesheet">


</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Mkulima</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <ul class="navbar-nav px-3" style="display: flex; flex-direction: row; align-items: center;">
            {% if user.is_authenticated %}
            <li class="nav-item text-nowrap mt-3 mr-3">
                <img src="{{request.user.profile.image.url}}" alt="" id="profile" class="rounded-circle">
            </li>
            <li class="nav-item text-nowrap mt-3 mr-3">
                <a class="nav-link text-primary" href="{% url 'profile' %}">{{request.user.username}}</a>
            </li>
            <li class="nav-item text-nowrap mt-3 mr-3">
                <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
            </li>

            {% else %}
            <li class="nav-item text-nowrap mt-3 mr-3">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item text-nowrap mt-3 mr-3">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
        </ul>

    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                <span data-feather="home"></span> Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'warehouse' %}">
                                <span data-feather="file"></span>Warehouses
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'farmers:farmers' %}">
                                <span data-feather="file"></span> Produce
                            </a>
                        </li>


                    </ul>
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Summary</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'subscription' %}">
                               Subscriptions
                            </a>
                        </li>

                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Communications</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Farmer_Buyer_Connection' %}">
                                Connections Farmers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Farmer_WH_Owner_Connection' %}">
                               Connections Warehouses
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>

            <main class="offset-md-2 col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-2">
                <div class="container">
                    <div class="row mt-3 mb-3 text-center">
                        <div class="col-md-6">
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}

                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>

                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-11 mb-10">

                            {% block content %} {% endblock content %}

                        </div>
                    </div>
                </div>
            </main>


            <script src="{% static 'users/js/jquery.min.js' %}"></script>

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js" integrity="sha512-GMGzUEevhWh8Tc/njS0bDpwgxdCJLQBWG3Z2Ct+JGOpVnEmjvNx6ts4v6A2XJf1HOrtOsfhv3hBKpK9kE5z8AQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</body>

</html>

users/templates/users/home.html
{% extends "users/base.html" %}
<title>
    {% block title %} Home {% endblock title%}
</title>

{% block content %}
<h1>Hello World</h1>
{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %} {% load static %}
<title>{% block title %} Login {% endblock title %}</title>{% load crispy_forms_tags %} {% block content %}

<div class="row mb-5">
    <div class="col-md-4 offset-md-4">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="text-center">Login</h2>
                <form action="" method="post">
                    {% csrf_token %} {{form|crispy}}
                    <div class="row mt-6 mb-2">
                        <div class="col">
                            <button type="submit" class="btn btn-sm btn-primary">Login</button>
                        </div>
                        <div class="col"><small><a href="{% url 'password_reset' %}">Forgot password</a></small></div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

users/templates/users/logout.html
{% extends "users/base.html" %}
<title>{% block title %} Logout {% endblock title %}</title> {% load crispy_forms_tags %} {% block content %}
<div class="card mt-4 p-2">
    <div class="head">
        <h4 class="pb-2">Logout</h4>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div>
                <h5>You have been logged out</h5>
                <small>Would You Like To Login Again
                    <a href="{% url 'login' %}">login</a>
                </small>
            </div>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "users/base.html" %} {% load static %}
<title>{% block title %} Instructions {% endblock title %}</title>{% load crispy_forms_tags %} {% block content %}

<div class="row mb-5">
    <div class="col-md-4 offset-md-4">
        <div class="card mt-2">
            <div class="card-body">
                <h5 class="text-center">Enter Email For Password Reset Instructions</h5>
                <form action="" method="post">
                    {% csrf_token %} {{form|crispy}}
                    <div class="row mt-6 mb-2">
                        <div class="col-md-12 ml-0">
                            <button type="submit" class="btn btn-sm btn-primary">Request For Reset Instructions</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "users/base.html" %} {% load static %}
<title>{% block title %} Instructions {% endblock title %}</title>{% load crispy_forms_tags %} {% block content %}

<div class="row mb-5">
    <div class="col-md-4 offset-md-4">
        <div class="card mt-2">
            <div class="card-body">
                <h6 class="text-center">Your Password Has Been Reset Successfuly</h6>

                <div class="row mt-6 mb-2">
                    <div class="col-md-12 ml-0">
                        <small><a href="{% url 'login' %}">Login Here</a></small>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %} {% load static %}
<title>{% block title %} Reset Password {% endblock title %}</title>{% load crispy_forms_tags %} {% block content %}

<div class="row mb-5">
    <div class="col-md-4 offset-md-4">
        <div class="card mt-2">
            <div class="card-body">
                <h5 class="text-center">Reset Password</h5>
                <form action="" method="post">
                    {% csrf_token %} {{form|crispy}}
                    <div class="row mt-6 mb-2">
                        <div class="col-md-12 ml-0">
                            <button type="submit" class="btn btn-sm btn-primary">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "users/base.html" %}
<title>{% block title %} Password Reset {% endblock title %}</title> {% load crispy_forms_tags %} {% block content %}
<div class="card mt-2 pt-2 pb-2">

    <div class="container">
        <div class="head">
            <h4>View Instructions</h4>
        </div>
        <form method="post">
            <div class="row mt-2">
                <div class="col-md-6">
                    <div class="alert alert-success">
                        An email has been sent to you. Follow instructions to reset your password.

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "users/base.html" %}
<title>
    {% block title %} Profile {% endblock title%}
</title> {% load crispy_forms_tags %} {% block content %}



<div class="row mt-3 mb-3">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <h4 class="text-center">
                    My <span class="text-primary">Profile</span>
                </h4>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <div class="image text-center">
                    <img src="{{user.profile.image.url}}" alt="" class="rounded-circle">
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <span class="font-weight-bold">username: </span>

                <span>{{user.username}}</span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <span class="font-weight-bold">email: </span>

                <span>{{user.email}}</span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <span class="font-weight-bold">occupation: </span>

                <span>{{user.profile.occupation}}</span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <span class="font-weight-bold">age: </span>

                <span>{{user.profile.age}}</span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <span class="font-weight-bold">Account Type: </span>

                <span>{{user.profile.accountType}}</span>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <h4 class="text-center">
                    <span class="text-primary">Update</span> Profile
                </h4>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-10 offset-md-2">
                <div class="card mt-3">
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %} {{u_form|crispy}}{{p_form|crispy}}
                            <div class="row mt-6 mb-2">
                                <div class="col-md-12 ml-0">
                                    <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends "users/base.html" %} {% load static %}
<title>{% block title %} Register {% endblock title %}</title>{% load crispy_forms_tags %} {% block content %}

<div class="row mb-5">
    <div class="col-md-4 offset-md-4">
        <div class="card mt-2">
            <div class="card-body">
                <h2 class="text-center">Register Here</h2>
                <form action="" method="post">
                    {% csrf_token %} {{form|crispy}}
                    <div class="row mt-6 mb-2">
                        <div class="col-md-12 ml-0">
                            <button id="register" type="submit" class="btn btn-sm btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'authentication/js/register.js' %}"></script>
{% endblock content %}