farmers/urls.py
from django.urls import path
from . import views


app_name = 'farmers'

urlpatterns = [
    path('', views.IndexView.as_view(), name='farmers'),
    path('add/', views.AddView.as_view(), name='add-farmer'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('<slug:pk>/', views.SingleView.as_view(), name='details-farmers'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit-farmer'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete-farmer'),
]

mkulima/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("subscriptions/", include("subscription_app.urls")),
    path('warehouses/', include("warehouses.urls")),
    path('connections/', include("farmer_connections.urls")),
    path("farmers/", include("farmers.urls")),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="users/password_reset.html"), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html"), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete")
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users import views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home, name="home"),
    path('profile/', views.profile, name="profile"),
    path('register/', views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(
        template_name="users/logout.html"), name="logout")
]

farmers/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Farmers(models.Model):
    produce = models.CharField(max_length=100)
    Price_per_kilo = models.IntegerField()
    Location = models.CharField(max_length=100)
    Contacts = models.IntegerField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='farmers')
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to="pics")

    def get_absolute_url(self):
        return reverse("farmers:details-farmers", kwargs={"pk": self.pk})

    class Meta:
        ordering = ['-published']  # ensure what is published latest come first

    def __str__(self):
        return self.produce

farmers/forms.py
from django import forms
from django.forms import fields
from .models import Farmers

class PostForm(forms.ModelForm):
    class Meta:
        model = Farmers
        fields= "__all__"

farmers/views.py
from django.urls.base import reverse
from .models import Farmers
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class IndexView(ListView):
    model = Farmers
    template_name = 'farmers/index.html'
    context_object_name = 'uploads'


class SingleView(DetailView):
    model = Farmers
    template_name = 'farmers/single.html'
    context_object_name = 'upload'


class PostsView(ListView):
    model = Farmers
    template_name = 'farmers/posts.html'
    context_object_name = 'post_list'


class AddView(LoginRequiredMixin, CreateView):
    model = Farmers
    template_name = 'farmers/add.html'
    fields = ['produce', 'Price_per_kilo', 'Location', 'Contacts', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class EditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Farmers
    template_name = 'farmers/edit.html'
    fields = ['produce', 'Price_per_kilo', 'Location', 'Contacts', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class Delete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Farmers
    template_name = 'farmers/confirm-delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    # take user to post after submission
    success_url = reverse_lazy('farmers:posts')

farmers/templates/farmers/add.html
{% extends "users/base.html" %}
<title>
    {% block title %} Add Product {% endblock title%}
</title>
{% load crispy_forms_tags %} {% block content %}

<div class="row">
    <div class="col-md-10">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Produce</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add Product</li>
            </ol>
        </nav>

    </div>
</div>
<div class="row mt-3 mb-5">
    <div class="col-md-6 offset-md-2">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="text-center">Add Product</h2>
                <form action="" method="post">
                    {% csrf_token %} {{form|crispy}}
                    <div class="row mt-6 mb-2">
                        <div class="col-3 ml-0">
                            <button type="submit" class="btn btn-sm btn-primary">Add Product</button>
                        </div>
                        <div class="col-3 ml-0">
                            <a href="{% url 'home' %}" class="btn btn-sm btn-danger">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>



{% endblock content %}

farmers/templates/farmers/base.html
<!doctype html>
<html lang="en">
  <head>
   <title>Farmers app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
  {% include 'farmers/navbar.html'%}
  {%block content %}
  {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  {% include 'farmers/footer.html' %}
  </body>
</html>

farmers/templates/farmers/confirm-delete.html
{% extends "users/base.html" %}
<title>
    {% block title %} Delete Produce {% endblock title%}
</title>
{% load crispy_forms_tags %} {% block content %}

<div class="row">
    <div class="col-md-10">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Produce</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete Produce</li>
            </ol>
        </nav>

    </div>
</div>
<div class="row mt-3 mb-5">
    <div class="col-md-6 offset-md-2">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="text-center">Edit Produce</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-8 p-2">
                            <div class="alert alert-success">
                                <p>Are you sure you want to delete <strong><i>{{object}}</i></strong> </p>>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-6 mb-2">
                        <div class="col-4">
                            <button type="submit" class="btn btn-sm btn-danger">Yes,Delete</button>
                        </div>
                        <div class="col-4">
                            <a href="{% url 'farmers:details-farmers' object.id %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>


{% endblock content %}









<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm">
</form>

farmers/templates/farmers/edit.html
{% extends "users/base.html" %}
<title>
    {% block title %} Edit Produce {% endblock title%}
</title>
{% load crispy_forms_tags %} {% block content %}

<div class="row">
    <div class="col-md-10">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Produce</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Produce</li>
            </ol>
        </nav>

    </div>
</div>
<div class="row mt-3 mb-5">
    <div class="col-md-6 offset-md-2">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="text-center">Edit Produce</h2>
                <form method="post">
                    {% csrf_token %} {{form|crispy}}
                    <div class="row mt-6 mb-2">
                        <div class="col-md-12 ml-0">
                            <button type="submit" class="btn btn-sm btn-primary">Edit Produce</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>


{% endblock content %}

farmers/templates/farmers/footer.html
<div class="container">
    <footer class="pt-4 my-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Mkulima Web App
                <small class="d-block mb-3 text-muted"></small>
                </div>
                <div class="col-6 col-md">
                    <h5>Admin</h5>
                    <ul class="List-unstyled text-small">
                        <li><a class="text-muted" href="#">Post Admin</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About Us</h5>
                    <ul class="List-unstyled text-small">
                        <li><a class="text-muted" href="#">Farmers Page</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Products</h5>
                    <ul class="List-unstyled text-small">
                        <li><a class="text-muted" href="#">Sample Products</a></li>
                </div>
            </div>
        </div>
    </footer>
</div>

farmers/templates/farmers/index.html
{% extends 'users/base.html' %}
<title>
    {% block title %} Produce {% endblock title%}
</title> {% block content %}
<div class="row">
    <div class="col-md-10">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Produce</a></li>
                <li class="breadcrumb-item active" aria-current="page">Produce</li>
            </ol>
        </nav>

    </div>
    <div class="col-md-10">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'farmers:add-farmer' %}">Add Produce</a></li>
            </ol>
        </nav>

    </div>
</div>
<div class="row">
    {% for upload in uploads %}

    <div class="col-4">
        <div class="card p-4 mb-3" style="min-height: 420px;">
            <div class="card-header"></div>
            <div class="card-img-top">
                <img class="img-fluid" style="min-height: 200px;" src="{{upload.image.url}}">
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Produce: </span>

                    <span>{{upload.produce}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Price_per_kilo: </span>

                    <span>{{upload.Price_per_kilo}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Location: </span>

                    <span>{{upload.Location}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Contacts: </span>

                    <span>{{upload.Contacts}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-2">
                    <a href="{% url 'farmers:details-farmers' upload.id %}"><button class="btn btn-outline-dark">Details</button></a>
                </div>

            </div>


        </div>
    </div>


    {% endfor %}</div>
{% endblock %}

farmers/templates/farmers/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Farmers Products</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
        </li>
      </ul>
    </div>
  </nav>

farmers/templates/farmers/posts.html
{% extends 'farmers/base.html'%}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand">Post Administration</div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'farmers:add'%}">Add new product</a>
            </li>
        </ul>
    </div>
</nav>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
        {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="#" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="lead"><a class="text-dark" href="{% url 'farmers:single' post.pk%}">{{post.produce}}</a></h4>
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{{post.get_absolute_url}}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">View</a>
                            <a href="{% url 'farmers:edit' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit</a>
                            <a href="{% url 'farmers:delete' post.pk %}" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete</a>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

farmers/templates/farmers/single.html
{% extends "users/base.html" %}

<title>
    {% block title %} Farmer Detail {% endblock title%}
</title> {% block content %}
<div class="row">
    <div class="col-md-10">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Farmer</a></li>
                <li class="breadcrumb-item active" aria-current="page">Warehouses</li>
            </ol>
        </nav>

    </div>

</div>
<div class="row">

    <div class="col-6">
        <div class="card p-4 mb-3" style="min-height: 520px;">
            <div class="card-header">{{upload.produce}}</div>
            <div class="card-img-top">
                <img class="img-fluid" style="min-height: 300px;" src="{{upload.image.url}}">
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Produce: </span>

                    <span>{{upload.produce}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Price_per_kilo: </span>

                    <span>{{upload.Price_per_kilo}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Location: </span>

                    <span>{{upload.Location}}</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Contacts: </span>

                    <span>{{upload.Contacts}}</span>
                </div>
            </div>



            <div class="row mt-3">
                <div class="col-md-12">
                    <span class="font-weight-bold">Email: </span>

                    <span>{{upload.author.email }}</span>
                </div>
            </div>

            {% if request.user == upload.author %}

            <div class="row mt-3">
                <div class="col-2">
                    <a href="{% url 'farmers:edit-farmer' upload.id %}"><button class="btn btn-secondary">Edit</button></a>
                </div>
                <div class="col-2">
                    <a href="{% url 'farmers:delete-farmer' upload.id %}"><button class="btn btn-danger">Delete</button></a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>


</div>
{% endblock %}